version: "3.9"
services:
    isketch:
        image: "ghcr.io/isketch-app/isketch-app:latest"
        ports:
            - "8080:80/tcp"
        depends_on:
            - mssql
        environment:
            - IS_SQL_Pass=iSketch.app
            - IS_SQL_ServerHost=mssql
            - IS_SQL_User=sa
            - IS_SQL_DatabaseName=iSketch.app
    mssql:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
            - "11434:1433/tcp"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=iSketch.app
            - MSSQL_PID=Express
        volumes:
            - isketch-data:/var/opt/mssql
volumes:
    isketch-data:
